version: "3.7"

services:

  redis:
    image: redis
    container_name: awe-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  redis-commander:
    container_name: awe-redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  server:
    container_name: awe
    build:
      context: ./
    env_file:
      - .env
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - DB_HOST=host.docker.internal
    ports:
     - "5000:5000"
    volumes:
      - ./:/var/app
    depends_on:
      - redis